name: 'Googletest installer'
description: 'Build and install googletest'
outputs:
  library_dir:
    description: 'The directory where the googletest libraries are located'
  include_dir:
    description: 'The googletest include directory'
runs:
  using: "composite"
  steps:
    - name: clone gtest
      run: git clone https://github.com/google/googletest
      shell: bash
    - name: configure gtest
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          cmake . -B build
        else
          sudo cmake -DCMAKE_BUILD_TYPE=Release . -B build
        fi
      working-directory: googletest
      shell: bash
    - name: build gtest
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          cmake --build . --config Release
        else
          sudo cmake --build .
        fi
      working-directory: googletest/build
      shell: bash
    - name: copy deps
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo cp googletest/build/lib/*.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
          sudo cp -R googletest/googletest/include/gtest /usr/include
        elif [ "$RUNNER_OS" == "Windows" ]; then
          mkdir D:/gtest
          mkdir D:/gtest/lib
          mkdir D:/gtest/include
          cp -R googletest/googletest/include/gtest D:/gtest/include
          cp googletest/build/lib/Release/gtest.lib D:/gtest/lib
          cp googletest/build/lib/Release/gtest_main.lib D:/gtest/lib
        else
          sudo cp googletest/build/lib/libgtest.a /usr/local/lib/libgtest.a
          sudo cp googletest/build/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
          sudo cp -R googletest/googletest/include/gtest /usr/local/include
        fi
      shell: bash
    - name: clean up
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          rm -R googletest
        else
          sudo rm -R googletest
        fi
branding:
  icon: activity
  color: gray-dark
