name: test

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macOS-latest
          - os: ubuntu-latest
          - os: windows-latest
            compiler: msvc
          - os: windows-latest
            compiler: mingw

    steps:
      - uses: actions/checkout@v2
      - name: Install googletest not macOs
        uses: ./
        if: matrix.os != 'macOs-latest' && matrix.compiler != 'mingw'
      - name: Install googletest mingw
        uses: ./
        if: matrix.compiler == 'mingw'
        with:
          GENERATOR: 'MinGW Makefiles'
      - name: install gcc-10 on macOs
        if: matrix.os == 'macOs-latest'
        run: brew install gcc@10
      - name: install googletest macOs
        if: matrix.os == 'macOs-latest'
        uses: ./
        with: # Set CC_path and CXX_path to gcc-10 and g++-10
          CC_path: /usr/local/bin/gcc-10
          CXX_path: /usr/local/bin/g++-10

      - name: configure test ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" . -B build
        working-directory: test
      - name: configure test macOs
        if: matrix.os == 'macOs-latest'
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" . -B build
        working-directory: test
        env:
          CC: /usr/local/bin/gcc-10
          CXX: /usr/local/bin/g++-10
      - name: build test not windows
        if: matrix.os != 'windows-latest'
        run: cmake --build .
        working-directory: test/build
      - name: configure windows msvc
        run: cmake . -B build
        if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
        working-directory: test
      - name: configure windows mingw
        run: cmake -G "MinGW Makefiles" . -B build
        if: matrix.os == 'windows-latest' && matrix.compiler == 'mingw'
        working-directory: test
      - name: build windows
        if: matrix.os == 'windows-latest'
        run: cmake --build . --config Release
        working-directory: test/build
      - name: run test not windows
        if: matrix.os != 'windows-latest'
        run: ./test
        working-directory: test/build
      #- name: run test windows
      #  if: matrix.os == 'windows-latest'
      #  run: test.exe
      #  working-directory: test/build
      #  shell: cmd
