name: test

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install googletest
        uses: MarkusJx/googletest-installer@latest
        id: install_gtest
      - name: echo library_dir
        if: matrix.os == 'windows-latest'
        run: "echo \"Library_dir: ${{ steps.install_gtest.outputs.library_dir }}\""
      - name: echo include_dir
        if: matrix.os == 'windows-latest'
        run: "echo \"Include_dir: ${{ steps.install_gtest.outputs.include_dir }}\""
